package GUI;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import user_manager.User;

public class UserDialog extends javax.swing.JDialog {

    private int SelectedOption = JOptionPane.CANCEL_OPTION;
    private user_manager.User user;
    private boolean editMood = false;

    public int EditUser(user_manager.User user) {
        editMood = true;
        try {
            this.user = user.clone();
        } catch (CloneNotSupportedException ex) {
            System.out.println("shit chone");
        }
        User_HomeDir.setText(user.getHomeDir());
        User_Home_Phone_Number.setText(user.getHomePhoneNumber());
        User_Name.setText(user.getName());
        User_Name.setEnabled(false);
        User_Other_Info.setText(user.getOtherInformation());
        User_Phone_Number.setText(user.getPhoneNumber());
        User_Phone_Number.setEnabled(false);
        User_Room_Number.setText(user.getRoomNumber());
        User_UserID.setValue(user.getID());
        User_Username.setText(user.getUsername());
        User_Password.setEnabled(false);
        CheckBox_Change_Password_Expire.setSelected(true);
        User_PE_Min.setValue(user.getMinExpireDays());
        User_PE_Max.setValue(user.getMaxExpireDays());
        User_PE_Warn.setValue(user.getWarningExpireDays());
        this.setVisible(true);
        return SelectedOption;
    }

    public int AddUser() {

        User_HomeDir.setEnabled(false);
        User_UserID.setEnabled(false);
        //User_UserID_Label.setVisible(false);
        this.setVisible(true);
        return SelectedOption;
    }

    public user_manager.User getUser() {
        return user;
    }

    private void UpdateUser() {
        user.setHomeDir(User_HomeDir.getText())
                .setHomePhoneNumber(User_Home_Phone_Number.getText())
                .setID((int) User_UserID.getValue())
                .setName(User_Name.getText())
                .setOtherInformation(User_Password.getText())
                .setPhoneNumber(User_Phone_Number.getText())
                .setRoomNumber(User_Room_Number.getText())
                .setUsername(User_Username.getText())
                .setPassword(User_Password.getText())
                .setMinExpireDays((int) User_PE_Min.getValue())
                .setMaxExpireDays((int) User_PE_Max.getValue())
                .setWarningExpireDays((int) User_PE_Warn.getValue());
    }

    public UserDialog() {
        user = new User();
        setModal(true);
        setAlwaysOnTop(true);
        initComponents();
        CheckBox_Change_Password_Expire.setSelected(false);
        CheckBox_Change_Password_ExpireActionPerformed(new ActionEvent(CheckBox_Change_Password_Expire, 0, null));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        User_Panel = new javax.swing.JPanel();
        Password_Panel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        User_PE_Min = new javax.swing.JSpinner();
        User_PE_Max = new javax.swing.JSpinner();
        User_PE_Warn = new javax.swing.JSpinner();
        User_Phone_Number = new javax.swing.JTextField();
        User_Home_Phone_Number = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        User_Name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        User_Room_Number = new javax.swing.JTextField();
        User_Password_Label = new javax.swing.JLabel();
        User_Password = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        User_UserID_Label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        User_HomeDir_Label = new javax.swing.JLabel();
        User_HomeDir = new javax.swing.JTextField();
        User_Username = new javax.swing.JTextField();
        User_UserID = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        User_Other_Info = new javax.swing.JTextField();
        CheckBox_Change_Password_Expire = new javax.swing.JCheckBox();
        Confirm_Panel = new javax.swing.JPanel();
        Btn_OK = new javax.swing.JToggleButton();
        Btn_Cancel = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Dialog");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(40, 40));
        setModal(true);

        User_Panel.setBackground(new java.awt.Color(255, 255, 255));
        User_Panel.setMinimumSize(new java.awt.Dimension(100, 100));

        Password_Panel.setBackground(java.awt.Color.white);
        Password_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Password Expiration details"));

        jLabel12.setText("Min days : ");

        jLabel13.setText("Max days : ");

        jLabel14.setText("Warning days : ");

        User_PE_Min.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        User_PE_Max.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        User_PE_Warn.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout Password_PanelLayout = new javax.swing.GroupLayout(Password_Panel);
        Password_Panel.setLayout(Password_PanelLayout);
        Password_PanelLayout.setHorizontalGroup(
            Password_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Password_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Password_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Password_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(User_PE_Min)
                    .addComponent(User_PE_Max, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(User_PE_Warn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        Password_PanelLayout.setVerticalGroup(
            Password_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Password_PanelLayout.createSequentialGroup()
                .addGroup(Password_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(User_PE_Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Password_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(User_PE_Max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Password_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(User_PE_Warn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel9.setText("Home Number : ");

        jLabel10.setText("Room Number : ");

        User_Password_Label.setText("Password : ");

        jLabel8.setText("Phone Number : ");

        jLabel3.setText("Username : ");

        User_UserID_Label.setText("UserID : ");

        jLabel5.setText("Name : ");

        User_HomeDir_Label.setText("Home directory : ");

        User_UserID.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel15.setText("Other Info : ");

        CheckBox_Change_Password_Expire.setBackground(new java.awt.Color(255, 255, 255));
        CheckBox_Change_Password_Expire.setSelected(true);
        CheckBox_Change_Password_Expire.setText("Add password expiration details");
        CheckBox_Change_Password_Expire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_Change_Password_ExpireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout User_PanelLayout = new javax.swing.GroupLayout(User_Panel);
        User_Panel.setLayout(User_PanelLayout);
        User_PanelLayout.setHorizontalGroup(
            User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(User_PanelLayout.createSequentialGroup()
                        .addComponent(CheckBox_Change_Password_Expire)
                        .addGap(0, 205, Short.MAX_VALUE))
                    .addGroup(User_PanelLayout.createSequentialGroup()
                        .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(User_Password_Label)
                            .addComponent(jLabel10)
                            .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(User_HomeDir_Label)
                                    .addComponent(User_UserID_Label))
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(User_Name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(User_HomeDir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(User_Username)
                            .addComponent(User_Room_Number, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(User_Home_Phone_Number, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(User_Phone_Number, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(User_Password, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(User_UserID)
                            .addComponent(User_Other_Info, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(Password_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        User_PanelLayout.setVerticalGroup(
            User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(User_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_UserID_Label)
                    .addComponent(User_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(User_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_HomeDir_Label)
                    .addComponent(User_HomeDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(User_Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(User_Home_Phone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(User_Room_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_Password_Label)
                    .addComponent(User_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(User_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(User_Other_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBox_Change_Password_Expire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Btn_OK.setText("Ok");
        Btn_OK.setPreferredSize(new java.awt.Dimension(80, 23));
        Btn_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OKActionPerformed(evt);
            }
        });

        Btn_Cancel.setText("Cancel");
        Btn_Cancel.setPreferredSize(new java.awt.Dimension(80, 23));
        Btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Confirm_PanelLayout = new javax.swing.GroupLayout(Confirm_Panel);
        Confirm_Panel.setLayout(Confirm_PanelLayout);
        Confirm_PanelLayout.setHorizontalGroup(
            Confirm_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Confirm_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_OK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Confirm_PanelLayout.setVerticalGroup(
            Confirm_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Confirm_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Confirm_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_OK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(User_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Confirm_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(User_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Confirm_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Close() {
        this.setVisible(false);
        dispose();
    }
    private void Btn_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OKActionPerformed
        String errors = "";

        if (User_Username.getText().equals("")) {
            errors += "Username, ";
        } else if (!editMood) {
            if (User_Name.getText().equals("")) {
                errors += "Name, ";
            } else if (User_Home_Phone_Number.getText().equals("")) {
                errors += "Home phone number, ";
            } else if (User_Password.getText().equals("")) {
                errors += "Password, ";
            } else if (User_Phone_Number.getText().equals("")) {
                errors += "Phone number, ";
            } else if (User_Room_Number.getText().equals("")) {
                errors += "Room Number";
            }
        }
        if (!"".equals(errors)) {
            JOptionPane.showMessageDialog(this, "Please, fill all required fields(" + errors + ").", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SelectedOption = JOptionPane.OK_OPTION;
        UpdateUser();
        Close();
    }//GEN-LAST:event_Btn_OKActionPerformed

    private void Btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelActionPerformed
        SelectedOption = JOptionPane.CANCEL_OPTION;
        Close();
    }//GEN-LAST:event_Btn_CancelActionPerformed

    private void CheckBox_Change_Password_ExpireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_Change_Password_ExpireActionPerformed
        Password_Panel.setEnabled(CheckBox_Change_Password_Expire.getModel().isSelected());

        for (java.awt.Component c : Password_Panel.getComponents()) {
            c.setEnabled(Password_Panel.isEnabled());
        }
    }//GEN-LAST:event_CheckBox_Change_Password_ExpireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Btn_Cancel;
    private javax.swing.JToggleButton Btn_OK;
    private javax.swing.JCheckBox CheckBox_Change_Password_Expire;
    private javax.swing.JPanel Confirm_Panel;
    private javax.swing.JPanel Password_Panel;
    private javax.swing.JTextField User_HomeDir;
    private javax.swing.JLabel User_HomeDir_Label;
    private javax.swing.JTextField User_Home_Phone_Number;
    private javax.swing.JTextField User_Name;
    private javax.swing.JTextField User_Other_Info;
    private javax.swing.JSpinner User_PE_Max;
    private javax.swing.JSpinner User_PE_Min;
    private javax.swing.JSpinner User_PE_Warn;
    private javax.swing.JPanel User_Panel;
    private javax.swing.JTextField User_Password;
    private javax.swing.JLabel User_Password_Label;
    private javax.swing.JTextField User_Phone_Number;
    private javax.swing.JTextField User_Room_Number;
    private javax.swing.JSpinner User_UserID;
    private javax.swing.JLabel User_UserID_Label;
    private javax.swing.JTextField User_Username;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
